Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -80,9 +80,17 @@ jobs:
         if [ ${{ env.REPO_NAME }} == "manifests" ]; then
           cd .repo/manifests                                                                                                                                    
           git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch                                                                          
-          git merge pr-branch                                                                                                                                
+          echo "git cherry-pick -x pr-branch"
+          set +e
+          cp_pr_result=$(git cherry-pick -x pr-branch 2>&1)
+          cp_pr_code=$?
+          echo $cp_pr_result
+          safe_cp_pr_result=$(echo "$cp_pr_result" | tr -d '\n' | tr -d '\r' | sed 's/[]\$`"\\]//g') # 格式化结果
+          echo "CP_PR_RESULT=$safe_cp_pr_result" >> $GITHUB_ENV
+          echo "CP_PR_CODE=$cp_pr_code" >> $GITHUB_ENV
           cd -                                                                                                                                                  
           ~/bin/repo sync -c -d --no-tags -j12
+          echo "REPO_SYNC_CODE=$?" >> $GITHUB_ENV
         else
           manifest_content=$(cat .repo/manifests/openvela.xml)
           echo $manifest_content
@@ -90,8 +98,37 @@ jobs:
           echo $REPO_PATH
           cd $REPO_PATH
           git fetch openvela pull/${{ github.event.pull_request.number }}/head:pr-branch
-          git checkout pr-branch
+          echo "git cherry-pick -x pr-branch"
+          set +e
+          cp_pr_result=$(git cherry-pick -x pr-branch 2>&1)
+          cp_pr_code=$?
+          echo $cp_pr_result
+          safe_cp_pr_result=$(echo "$cp_pr_result" | tr -d '\n' | tr -d '\r' | sed 's/[]\$`"\\]//g') # 格式化结果
+          echo "CP_PR_RESULT=$safe_cp_pr_result" >> $GITHUB_ENV
+          echo "CP_PR_CODE=$cp_pr_code" >> $GITHUB_ENV
           cd -
+        fi
+      continue-on-error: true
+
+    - name: check cherry-pick pr result
+      run: |
+        if [ ${{ env.REPO_SYNC_CODE }} == 0 ]; then
+          echo "repo sync after cherry-pick manifest PR success."
+        else
+          echo "repo sync after cherry-pick manifest PR failed."
+          exit 1
+        fi
+        if [ ${{ env.CP_PR_CODE }} == 0 ]; then
+          echo "cherry-pick PR success and continue."
+        else
+          echo "${{ env.CP_PR_RESULT }}" | grep "is a merge"
+          if [ $? -eq 0 ]; then
+            echo "There's merge commit in your PR. Please use rebase insteadof merge."
+            exit 1
+          else
+            echo "cherry-pick PR failed with error message: ${{ env.CP_PR_RESULT }}"
+            exit 1
+          fi
         fi
 
     - name: Docker Login                                                                                                                                                                                                 
